In [29]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

In [30]:
df = pd.read_csv('AB_NYC_2019.csv')

In [31]:
cols = list(['neighbourhood_group','room_type','latitude', 'longitude','price','minimum_nights','number_of_reviews','reviews_per_month','calculated_host_listings_count','availability_365'])
df = df[cols]
df.head()

neighbourhood_group        room_type  latitude  longitude  price  \
0            Brooklyn     Private room  40.64749  -73.97237    149   
1           Manhattan  Entire home/apt  40.75362  -73.98377    225   
2           Manhattan     Private room  40.80902  -73.94190    150   
3            Brooklyn  Entire home/apt  40.68514  -73.95976     89   
4           Manhattan  Entire home/apt  40.79851  -73.94399     80   

   minimum_nights  number_of_reviews  reviews_per_month  \
0               1                  9               0.21   
1               1                 45               0.38   
2               3                  0                NaN   
3               1                270               4.64   
4              10                  9               0.10   

   calculated_host_listings_count  availability_365  
0                               6               365  
1                               2               355  
2                               1               365  
3                               1               194  
4                               1                 0

In [32]:
df.isnull().sum()

neighbourhood_group                   0
room_type                             0
latitude                              0
longitude                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [33]:
df.reviews_per_month = df.reviews_per_month.fillna(0)

In [34]:
df.nunique()

neighbourhood_group                   5
room_type                             3
latitude                          19048
longitude                         14718
price                               674
minimum_nights                      109
number_of_reviews                   394
reviews_per_month                   938
calculated_host_listings_count       47
availability_365                    366
dtype: int64

<h1><b>Question 1</b></h1>
What is the most frequent observation (mode) for the column 'neighbourhood_group' ?

In [35]:
df.neighbourhood_group.value_counts()

Manhattan        21661
Brooklyn         20104
Queens            5666
Bronx             1091
Staten Island      373
Name: neighbourhood_group, dtype: int64

Split the data

    Split your data in train/val/test sets, with 60%/20%/20% distribution.
    Use Scikit-Learn for that (the train_test_split function) and set the seed to 42.
    Make sure that the target value ('price') is not in your dataframe.


In [36]:
from sklearn.model_selection import train_test_split

In [37]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)

In [38]:
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)

In [39]:
len(df_train), len(df_val), len(df_test)

(29337, 9779, 9779)

In [40]:
df_train.head()

neighbourhood_group        room_type  latitude  longitude  price  \
2777             Brooklyn  Entire home/apt  40.68084  -73.92804    170   
26060           Manhattan     Private room  40.82040  -73.93867     50   
39854            Brooklyn     Private room  40.69007  -73.94326     40   
31667           Manhattan     Private room  40.80931  -73.93982     65   
3790             Brooklyn  Entire home/apt  40.71969  -73.95830    500   

       minimum_nights  number_of_reviews  reviews_per_month  \
2777                3                134               2.00   
26060               1                  2               0.09   
39854               7                 13               2.39   
31667               4                  8               0.64   
3790                1                  0               0.00   

       calculated_host_listings_count  availability_365  
2777                                3               209  
26060                               1                 0  
39854                               1                93  
31667                               4                 0  
3790                                1                 0

In [41]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [42]:
y_train = df_train.price.values
y_val = df_val.price.values
y_test = df_test.price.values

y_train_q6 = np.log1p(y_train)
y_val_q6 = np.log1p(y_val)
y_test_q6 = np.log1p(y_test)

In [43]:
del df_train['price']
del df_val['price']
del df_test['price']

In [44]:
df_train.head()

neighbourhood_group        room_type  latitude  longitude  minimum_nights  \
0            Brooklyn  Entire home/apt  40.68084  -73.92804               3   
1           Manhattan     Private room  40.82040  -73.93867               1   
2            Brooklyn     Private room  40.69007  -73.94326               7   
3           Manhattan     Private room  40.80931  -73.93982               4   
4            Brooklyn  Entire home/apt  40.71969  -73.95830               1   

   number_of_reviews  reviews_per_month  calculated_host_listings_count  \
0                134               2.00                               3   
1                  2               0.09                               1   
2                 13               2.39                               1   
3                  8               0.64                               4   
4                  0               0.00                               1   

   availability_365  
0               209  
1                 0  
2                93  
3                 0  
4                 0

<h1><b>Question 2</b></h1>


    Create the correlation matrix for the numerical features of your train dataset.
        In a correlation matrix, you compute the correlation coefficient between every pair of features in the dataset.
    What are the two features that have the biggest correlation in this dataset?


In [415]:
df_train.dtypes

neighbourhood_group                object
room_type                          object
latitude                          float64
longitude                         float64
minimum_nights                      int64
number_of_reviews                   int64
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
dtype: object

In [18]:
numerical = ['latitude','longitude','minimum_nights','number_of_reviews','reviews_per_month','calculated_host_listings_count','availability_365']

In [19]:
df_numerical = df[numerical]
df_numerical.head()

latitude  longitude  minimum_nights  number_of_reviews  reviews_per_month  \
0  40.64749  -73.97237               1                  9               0.21   
1  40.75362  -73.98377               1                 45               0.38   
2  40.80902  -73.94190               3                  0               0.00   
3  40.68514  -73.95976               1                270               4.64   
4  40.79851  -73.94399              10                  9               0.10   

   calculated_host_listings_count  availability_365  
0                               6               365  
1                               2               355  
2                               1               365  
3                               1               194  
4                               1                 0

In [20]:
df_num_corr = df_numerical.corr()
df_num_corr

latitude  longitude  minimum_nights  \
latitude                        1.000000   0.084788        0.024869   
longitude                       0.084788   1.000000       -0.062747   
minimum_nights                  0.024869  -0.062747        1.000000   
number_of_reviews              -0.015389   0.059094       -0.080116   
reviews_per_month              -0.018758   0.138516       -0.124905   
calculated_host_listings_count  0.019517  -0.114713        0.127960   
availability_365               -0.010983   0.082731        0.144303   

                                number_of_reviews  reviews_per_month  \
latitude                                -0.015389          -0.018758   
longitude                                0.059094           0.138516   
minimum_nights                          -0.080116          -0.124905   
number_of_reviews                        1.000000           0.589407   
reviews_per_month                        0.589407           1.000000   
calculated_host_listings_count          -0.072376          -0.047312   
availability_365                         0.172028           0.163732   

                                calculated_host_listings_count  \
latitude                                              0.019517   
longitude                                            -0.114713   
minimum_nights                                        0.127960   
number_of_reviews                                    -0.072376   
reviews_per_month                                    -0.047312   
calculated_host_listings_count                        1.000000   
availability_365                                      0.225701   

                                availability_365  
latitude                               -0.010983  
longitude                               0.082731  
minimum_nights                          0.144303  
number_of_reviews                       0.172028  
reviews_per_month                       0.163732  
calculated_host_listings_count          0.225701  
availability_365                        1.000000

What are the two features that have the biggest correlation in this dataset? number_of_reviews and reviews_per_month

<b>Make price binary</b>

    We need to turn the price variable from numeric into binary.
    Let's create a variable above_average which is 1 if the price is above (or equal to) 152.


In [21]:
above_average = (y_train >= 152).astype(int) 

In [22]:
above_average

array([1, 0, 0, ..., 1, 0, 0])

<h1><b>Question 3</b></h1>


    Calculate the mutual information score with the (binarized) price for the two categorical variables that we have. Use the training set only.
    Which of these two variables has bigger score?
    Round it to 2 decimal digits using round(score, 2)


In [23]:
from sklearn.metrics import mutual_info_score

In [24]:
categorical = ['neighbourhood_group', 'room_type']
df_train[categorical].head()

neighbourhood_group        room_type
0            Brooklyn  Entire home/apt
1           Manhattan     Private room
2            Brooklyn     Private room
3           Manhattan     Private room
4            Brooklyn  Entire home/apt

In [25]:
mutual_info_score(above_average, df_train.room_type)

0.14257297658111734

In [26]:
def mutual_info_price_score(series):
    return round(mutual_info_score(above_average, series), 2)

In [27]:
mi = df_train[categorical].apply(mutual_info_price_score)
mi.sort_values(ascending=False)

room_type              0.14
neighbourhood_group    0.05
dtype: float64

<h1><b>Question 4</b></h1>


    Now let's train a logistic regression
    Remember that we have two categorical variables in the data. Include them using one-hot encoding.
    Fit the model on the training dataset.
        To make sure the results are reproducible across different versions of Scikit-Learn, fit the model with these parameters:
        model = LogisticRegression(solver='lbfgs', C=1.0, random_state=42)
    Calculate the accuracy on the validation dataset and rount it to 2 decimal digits.


In [17]:
from sklearn.feature_extraction import DictVectorizer

In [18]:
y_train = (y_train >= 152).astype(int)
y_val = (y_val >= 152).astype(int) 

In [20]:
numerical = ['latitude','longitude','minimum_nights','number_of_reviews','reviews_per_month','calculated_host_listings_count','availability_365']
categorical = ['neighbourhood_group', 'room_type']

In [21]:
train_dicts = df_train[categorical + numerical].to_dict(orient='records')
val_dicts = df_val[categorical + numerical].to_dict(orient='records')

In [212]:
train_dicts[:2]

[{'neighbourhood_group': 'Brooklyn',
  'room_type': 'Entire home/apt',
  'latitude': 40.68084,
  'longitude': -73.92804,
  'minimum_nights': 3,
  'number_of_reviews': 134,
  'reviews_per_month': 2.0,
  'calculated_host_listings_count': 3,
  'availability_365': 209},
 {'neighbourhood_group': 'Manhattan',
  'room_type': 'Private room',
  'latitude': 40.8204,
  'longitude': -73.93867,
  'minimum_nights': 1,
  'number_of_reviews': 2,
  'reviews_per_month': 0.09,
  'calculated_host_listings_count': 1,
  'availability_365': 0}]

In [22]:
dv = DictVectorizer(sparse=False)

In [23]:
X_train = dv.fit_transform(train_dicts)
X_val = dv.transform(val_dicts)

In [215]:
X_train

array([[209.     ,   3.     ,  40.68084, ...,   1.     ,   0.     ,
          0.     ],
       [  0.     ,   1.     ,  40.8204 , ...,   0.     ,   1.     ,
          0.     ],
       [ 93.     ,   1.     ,  40.69007, ...,   0.     ,   1.     ,
          0.     ],
       ...,
       [202.     ,   1.     ,  40.76662, ...,   1.     ,   0.     ,
          0.     ],
       [  0.     ,   1.     ,  40.68462, ...,   1.     ,   0.     ,
          0.     ],
       [235.     ,   3.     ,  40.82332, ...,   0.     ,   1.     ,
          0.     ]])

In [216]:
dv.get_feature_names()

['availability_365',
 'calculated_host_listings_count',
 'latitude',
 'longitude',
 'minimum_nights',
 'neighbourhood_group=Bronx',
 'neighbourhood_group=Brooklyn',
 'neighbourhood_group=Manhattan',
 'neighbourhood_group=Queens',
 'neighbourhood_group=Staten Island',
 'number_of_reviews',
 'reviews_per_month',
 'room_type=Entire home/apt',
 'room_type=Private room',
 'room_type=Shared room']

In [24]:
from sklearn.linear_model import LogisticRegression

In [25]:
model = LogisticRegression(solver='lbfgs', C=1.0, random_state=42)

In [26]:
model.fit(X_train, y_train)

/home/germano/anaconda3/envs/ml-zoomcamp/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=42)

In [27]:
model.predict_proba(X_val)

array([[0.46940369, 0.53059631],
       [0.45671578, 0.54328422],
       [0.6101165 , 0.3898835 ],
       ...,
       [0.62532975, 0.37467025],
       [0.80194108, 0.19805892],
       [0.63661784, 0.36338216]])

In [28]:
y_pred = model.predict(X_val)

In [29]:
y_prob = model.predict_proba(X_val)[:, 1]
y_prob

array([0.53059631, 0.54328422, 0.3898835 , ..., 0.37467025, 0.19805892,
       0.36338216])

In [30]:
df_pred = pd.DataFrame()
df_pred['probability'] = y_prob
df_pred['prediction'] = y_pred
df_pred['actual'] = y_val
df_pred['correct'] = df_pred.prediction == df_pred.actual
round(df_pred['correct'].mean(), 2)

0.79

<h1><b>Question 5</b></h1>

    We have 9 features: 7 numerical features and 2 categorical.
    Let's find the least useful one using the feature elimination technique.
    Train a model with all these features (using the same parameters as in Q4).
    Now exclude each feature from this set and train a model without it. Record the accuracy for each model.
    For each feature, calculate the difference between the original accuracy and the accuracy without the feature.
    Which of following feature has the smallest difference?
        neighbourhood_group
        room_type
        number_of_reviews
        reviews_per_month

    note: the difference doesn't have to be positive


In [237]:
df_full_train = df_full_train.reset_index(drop=True)
df_full_train.head()

neighbourhood_group        room_type  latitude  longitude  price  \
0            Brooklyn  Entire home/apt  40.71577  -73.95530    295   
1           Manhattan     Private room  40.84917  -73.94048     70   
2            Brooklyn     Private room  40.68993  -73.95947     58   
3            Brooklyn  Entire home/apt  40.68427  -73.93118     75   
4              Queens     Private room  40.74705  -73.89564     38   

   minimum_nights  number_of_reviews  reviews_per_month  \
0               3                 11               0.87   
1               2                  2               0.16   
2               2                  0               0.00   
3               3                 87               4.91   
4               5                 13               0.25   

   calculated_host_listings_count  availability_365  
0                               1                 1  
1                               1                 0  
2                               2                 0  
3                               1               267  
4                               1                 0

In [238]:
def mutual_info_price_score(series):
    return mutual_info_score(df_full_train.price, series)

In [239]:
mi = df_full_train[categorical].apply(mutual_info_price_score)
mi.sort_values(ascending=False)

room_type              0.311407
neighbourhood_group    0.105645
dtype: float64

In [240]:
df_full_train[numerical].corrwith(df_full_train.price)

latitude                          0.035015
longitude                        -0.149080
minimum_nights                    0.042740
number_of_reviews                -0.048926
reviews_per_month                -0.051978
calculated_host_listings_count    0.055336
availability_365                  0.080562
dtype: float64

In [241]:
dv.get_feature_names()

['availability_365',
 'calculated_host_listings_count',
 'latitude',
 'longitude',
 'minimum_nights',
 'neighbourhood_group=Bronx',
 'neighbourhood_group=Brooklyn',
 'neighbourhood_group=Manhattan',
 'neighbourhood_group=Queens',
 'neighbourhood_group=Staten Island',
 'number_of_reviews',
 'reviews_per_month',
 'room_type=Entire home/apt',
 'room_type=Private room',
 'room_type=Shared room']

In [242]:
model.coef_[0].round(3)

array([ 0.003,  0.005, -0.153, -0.056, -0.014, -0.277, -0.009,  1.025,
       -0.656, -0.085, -0.003, -0.079,  1.646, -1.325, -0.323])

In [243]:
dict(zip(dv.get_feature_names(), model.coef_[0].round(3)))

{'availability_365': 0.003,
 'calculated_host_listings_count': 0.005,
 'latitude': -0.153,
 'longitude': -0.056,
 'minimum_nights': -0.014,
 'neighbourhood_group=Bronx': -0.277,
 'neighbourhood_group=Brooklyn': -0.009,
 'neighbourhood_group=Manhattan': 1.025,
 'neighbourhood_group=Queens': -0.656,
 'neighbourhood_group=Staten Island': -0.085,
 'number_of_reviews': -0.003,
 'reviews_per_month': -0.079,
 'room_type=Entire home/apt': 1.646,
 'room_type=Private room': -1.325,
 'room_type=Shared room': -0.323}

In [122]:
y_train = (y_train >= 152).astype(int)
y_val = (y_val >= 152).astype(int) 

In [31]:
features = ['latitude','longitude','minimum_nights','number_of_reviews','reviews_per_month','calculated_host_listings_count','availability_365','neighbourhood_group', 'room_type']

In [32]:
train_dicts = df_train[features].to_dict(orient='records')
val_dicts = df_val[features].to_dict(orient='records')

In [33]:
dv = DictVectorizer(sparse=False)

In [34]:
X_train = dv.fit_transform(train_dicts)
X_val = dv.transform(val_dicts)


In [35]:
model = LogisticRegression(solver='lbfgs', C=1.0, random_state=42)

In [36]:
model.fit(X_train, y_train)

/home/germano/anaconda3/envs/ml-zoomcamp/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=42)

In [37]:
y_pred = model.predict(X_val)
y_prob = model.predict_proba(X_val)[:, 1]


In [38]:
df_pred = pd.DataFrame()
df_pred['probability'] = y_prob
df_pred['prediction'] = y_pred
df_pred['actual'] = y_val
df_pred['correct'] = df_pred.prediction == df_pred.actual
round(df_pred['correct'].mean(), 2)

0.79

#####


In [120]:
import time

In [128]:
features = ['latitude','longitude','minimum_nights','number_of_reviews','reviews_per_month','calculated_host_listings_count','availability_365','neighbourhood_group', 'room_type']
features = ['number_of_reviews','reviews_per_month','neighbourhood_group', 'room_type']
original_accuracy = 0.790878412925657

In [129]:
i = 0
while i < len(features):
    
    print(features)
    
    train_dicts = df_train[features].to_dict(orient='records')
    val_dicts = df_val[features].to_dict(orient='records')
    dv = DictVectorizer(sparse=False)
    X_train = dv.fit_transform(train_dicts)
    X_val = dv.transform(val_dicts)
    model = LogisticRegression(solver='lbfgs', C=1.0, random_state=42)
    model.fit(X_train, y_train)
    time.sleep(5)
    y_pred = model.predict(X_val)
    y_prob = model.predict_proba(X_val)[:, 1]
    df_pred = pd.DataFrame()
    df_pred['probability'] = y_prob
    df_pred['prediction'] = y_pred
    df_pred['actual'] = y_val
    df_pred['correct'] = df_pred.prediction == df_pred.actual
    print(original_accuracy - df_pred['correct'].mean())

    del features[i]

['number_of_reviews', 'reviews_per_month', 'neighbourhood_group', 'room_type']


/home/germano/anaconda3/envs/ml-zoomcamp/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.0015338991716944417
['reviews_per_month', 'neighbourhood_group', 'room_type']
0.0014316392269148048
['neighbourhood_group', 'room_type']
0.0014316392269148048
['room_type']
0.06595766438286121


In [130]:
original_accuracy = 0.790878412925657

def accuracy(features):
    print(features)
    
    train_dicts = df_train[features].to_dict(orient='records')
    val_dicts = df_val[features].to_dict(orient='records')
    dv = DictVectorizer(sparse=False)
    X_train = dv.fit_transform(train_dicts)
    X_val = dv.transform(val_dicts)
    model = LogisticRegression(solver='lbfgs', C=1.0, random_state=42)
    model.fit(X_train, y_train)
    time.sleep(5)
    y_pred = model.predict(X_val)
    y_prob = model.predict_proba(X_val)[:, 1]
    df_pred = pd.DataFrame()
    df_pred['probability'] = y_prob
    df_pred['prediction'] = y_pred
    df_pred['actual'] = y_val
    df_pred['correct'] = df_pred.prediction == df_pred.actual
    print(original_accuracy - df_pred['correct'].mean())

In [131]:
accuracy(['latitude','longitude','minimum_nights','number_of_reviews','reviews_per_month','calculated_host_listings_count','availability_365','neighbourhood_group', 'room_type'])

['latitude', 'longitude', 'minimum_nights', 'number_of_reviews', 'reviews_per_month', 'calculated_host_listings_count', 'availability_365', 'neighbourhood_group', 'room_type']


/home/germano/anaconda3/envs/ml-zoomcamp/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.0


FULL: 0.0

In [132]:
accuracy(['latitude','longitude','minimum_nights','number_of_reviews','reviews_per_month','calculated_host_listings_count','availability_365', 'room_type'])

['latitude', 'longitude', 'minimum_nights', 'number_of_reviews', 'reviews_per_month', 'calculated_host_listings_count', 'availability_365', 'room_type']


/home/germano/anaconda3/envs/ml-zoomcamp/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.04223335719398702


neighbourhood_group: 0.04223335719398702

In [133]:
accuracy(['latitude','longitude','minimum_nights','number_of_reviews','reviews_per_month','calculated_host_listings_count','availability_365','neighbourhood_group'])

['latitude', 'longitude', 'minimum_nights', 'number_of_reviews', 'reviews_per_month', 'calculated_host_listings_count', 'availability_365', 'neighbourhood_group']


/home/germano/anaconda3/envs/ml-zoomcamp/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.07321812046221488


room_type : 0.07321812046221488

In [134]:
accuracy(['latitude','longitude','minimum_nights','reviews_per_month','calculated_host_listings_count','availability_365','neighbourhood_group', 'room_type'])

['latitude', 'longitude', 'minimum_nights', 'reviews_per_month', 'calculated_host_listings_count', 'availability_365', 'neighbourhood_group', 'room_type']


/home/germano/anaconda3/envs/ml-zoomcamp/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.0015338991716944417


number_of_reviews : 0.0015338991716944417

In [135]:
accuracy(['latitude','longitude','minimum_nights','number_of_reviews','calculated_host_listings_count','availability_365','neighbourhood_group', 'room_type'])

['latitude', 'longitude', 'minimum_nights', 'number_of_reviews', 'calculated_host_listings_count', 'availability_365', 'neighbourhood_group', 'room_type']


/home/germano/anaconda3/envs/ml-zoomcamp/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


-0.0005112997238981842


reviews_per_month: -0.0005112997238981842

<b>ANSWER: reviews_per_month: -0.0005112997238981842</b>

<h1><b>Question 6</b></h1>

    For this question, we'll see how to use a linear regression model from Scikit-Learn
    We'll need to use the original column 'price'. Apply the logarithmic transformation to this column.
    Fit the Ridge regression model on the training data.
    This model has a parameter alpha. Let's try the following values: [0, 0.01, 0.1, 1, 10]
    Which of these alphas leads to the best RMSE on the validation set? Round your RMSE scores to 3 decimal digits.

If there are multiple options, select the smallest alpha.

In [191]:
y_train_q6 , y_val_q6, y_test_q6

(array([5.14166356, 3.93182563, 3.71357207, ..., 5.19295685, 4.31748811,
        4.51085951]),
 array([5.62040087, 5.08140436, 5.01727984, ..., 4.30406509, 5.01727984,
        4.7095302 ]),
 array([4.49980967, 3.4339872 , 4.79579055, ..., 4.26267988, 6.2166061 ,
        4.83628191]))

In [45]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.feature_extraction import DictVectorizer

In [46]:
features = ['latitude','longitude','minimum_nights','number_of_reviews','reviews_per_month','calculated_host_listings_count','availability_365','neighbourhood_group', 'room_type']

In [47]:
train_dicts = df_train[features].to_dict(orient='records')
val_dicts = df_val[features].to_dict(orient='records')
dv = DictVectorizer(sparse=False)
X_train = dv.fit_transform(train_dicts)
X_val = dv.transform(val_dicts)

In [62]:
model = Ridge(alpha=1, normalize=True)

In [63]:
model.fit(X_train, y_train_q6)

Ridge(alpha=1, normalize=True)

In [65]:
w0 = model.intercept_
w0

-103.15647087524054

In [66]:
w = model.coef_
w

array([ 3.19357049e-04,  4.56053280e-04,  4.80565815e-02, -1.43171926e+00,
       -4.43093910e-04, -1.56253702e-01, -7.13931839e-02,  1.27082337e-01,
       -8.34319265e-02, -2.91232083e-01, -2.25334084e-04, -6.22365821e-03,
        2.74297405e-01, -2.40931639e-01, -3.74265845e-01])

In [67]:
y_pred = model.predict(X_val)
y_pred

array([4.97923392, 5.0518366 , 4.89114977, ..., 4.89640686, 4.73678124,
       4.88053701])

In [68]:
def rmse(y, y_pred):
    se = (y - y_pred) ** 2
    mse = se.mean()
    return np.sqrt(mse)

In [69]:
y_pred = w0 + X_val.dot(w)

In [70]:
rmse(y_val_q6, y_pred)

0.5306305788059253

In [86]:
train_dicts = df_train[features].to_dict(orient='records')
val_dicts = df_val[features].to_dict(orient='records')
dv = DictVectorizer(sparse=False)
X_train = dv.fit_transform(train_dicts)
X_val = dv.transform(val_dicts)
model = Ridge(alpha = 0, normalize=True)
model.fit(X_train, y_train_q6)
w0 = model.intercept_
w = model.coef_
y_pred = w0 + X_val.dot(w)
round(rmse(y_val_q6, y_pred), 3)

0.505

In [87]:
train_dicts = df_train[features].to_dict(orient='records')
val_dicts = df_val[features].to_dict(orient='records')
dv = DictVectorizer(sparse=False)
X_train = dv.fit_transform(train_dicts)
X_val = dv.transform(val_dicts)
model = Ridge(alpha = 0.01, normalize=True)
model.fit(X_train, y_train_q6)
w0 = model.intercept_
w = model.coef_
y_pred = w0 + X_val.dot(w)
round(rmse(y_val_q6, y_pred), 3)

0.505

In [88]:
train_dicts = df_train[features].to_dict(orient='records')
val_dicts = df_val[features].to_dict(orient='records')
dv = DictVectorizer(sparse=False)
X_train = dv.fit_transform(train_dicts)
X_val = dv.transform(val_dicts)
model = Ridge(alpha = 0.1, normalize=True)
model.fit(X_train, y_train_q6)
w0 = model.intercept_
w = model.coef_
y_pred = w0 + X_val.dot(w)
round(rmse(y_val_q6, y_pred), 3)

0.506

In [89]:
train_dicts = df_train[features].to_dict(orient='records')
val_dicts = df_val[features].to_dict(orient='records')
dv = DictVectorizer(sparse=False)
X_train = dv.fit_transform(train_dicts)
X_val = dv.transform(val_dicts)
model = Ridge(alpha = 1, normalize=True)
model.fit(X_train, y_train_q6)
w0 = model.intercept_
w = model.coef_
y_pred = w0 + X_val.dot(w)
round(rmse(y_val_q6, y_pred), 3)

0.531

In [90]:
train_dicts = df_train[features].to_dict(orient='records')
val_dicts = df_val[features].to_dict(orient='records')
dv = DictVectorizer(sparse=False)
X_train = dv.fit_transform(train_dicts)
X_val = dv.transform(val_dicts)
model = Ridge(alpha = 10, normalize=True)
model.fit(X_train, y_train_q6)
w0 = model.intercept_
w = model.coef_
y_pred = w0 + X_val.dot(w)
round(rmse(y_val_q6, y_pred), 3)

0.641