<h2><b>Session #1 Homework</b></h2>

<h3><b>Question 1</b></h3>

What's the version of NumPy that you installed?

In [2]:
import numpy as np

In [3]:
np.__version__

'1.20.3'

<h3><b>Question 2</b></h3>

What's the version of Pandas?

In [4]:
import pandas as pn

In [5]:
pn.__version__

'1.3.2'

<h3><b>Question 3</b></h3>

What's the average price of BMW cars in the dataset?

In [7]:
import os

In [8]:
fname = os.path.join("data.csv")

In [9]:
df = pn.read_csv(fname)

In [10]:
df

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [14]:
dfBMW = df[df['Make'] == 'BMW']

In [15]:
dfBMW

Make       Model  Year             Engine Fuel Type  Engine HP  \
0      BMW  1 Series M  2011  premium unleaded (required)      335.0   
1      BMW    1 Series  2011  premium unleaded (required)      300.0   
2      BMW    1 Series  2011  premium unleaded (required)      300.0   
3      BMW    1 Series  2011  premium unleaded (required)      230.0   
4      BMW    1 Series  2011  premium unleaded (required)      230.0   
...    ...         ...   ...                          ...        ...   
11901  BMW          Z4  2016  premium unleaded (required)      240.0   
11902  BMW          Z4  2016  premium unleaded (required)      335.0   
11903  BMW          Z8  2001  premium unleaded (required)      394.0   
11904  BMW          Z8  2002  premium unleaded (required)      394.0   
11905  BMW          Z8  2003  premium unleaded (required)      394.0   

       Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL  rear wheel drive              2.0   
1                   6.0            MANUAL  rear wheel drive              2.0   
2                   6.0            MANUAL  rear wheel drive              2.0   
3                   6.0            MANUAL  rear wheel drive              2.0   
4                   6.0            MANUAL  rear wheel drive              2.0   
...                 ...               ...               ...              ...   
11901               4.0            MANUAL  rear wheel drive              2.0   
11902               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   
11903               8.0            MANUAL  rear wheel drive              2.0   
11904               8.0            MANUAL  rear wheel drive              2.0   
11905               8.0            MANUAL  rear wheel drive              2.0   

                             Market Category Vehicle Size Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                         Luxury,Performance      Compact   Convertible   
2                    Luxury,High-Performance      Compact         Coupe   
3                         Luxury,Performance      Compact         Coupe   
4                                     Luxury      Compact   Convertible   
...                                      ...          ...           ...   
11901                     Luxury,Performance      Compact   Convertible   
11902                Luxury,High-Performance      Compact   Convertible   
11903         Exotic,Luxury,High-Performance      Compact   Convertible   
11904         Exotic,Luxury,High-Performance      Compact   Convertible   
11905         Exotic,Luxury,High-Performance      Compact   Convertible   

       highway MPG  city mpg  Popularity    MSRP  
0               26        19        3916   46135  
1               28        19        3916   40650  
2               28        20        3916   36350  
3               28        18        3916   29450  
4               28        18        3916   34500  
...            ...       ...         ...     ...  
11901           34        22        3916   49700  
11902           24        17        3916   66350  
11903           19        12        3916  128000  
11904           19        12        3916  130000  
11905           19        12        3916  131500  

[334 rows x 16 columns]

In [18]:
dfBMW['MSRP'].mean()

61546.76347305389

In [19]:
df.groupby('Make').MSRP.mean()

Make
Acura            3.488759e+04
Alfa Romeo       6.160000e+04
Aston Martin     1.979104e+05
Audi             5.345211e+04
BMW              6.154676e+04
Bentley          2.471693e+05
Bugatti          1.757224e+06
Buick            2.820661e+04
Cadillac         5.623132e+04
Chevrolet        2.835039e+04
Chrysler         2.672296e+04
Dodge            2.239006e+04
FIAT             2.267024e+04
Ferrari          2.382188e+05
Ford             2.739927e+04
GMC              3.049330e+04
Genesis          4.661667e+04
HUMMER           3.646441e+04
Honda            2.667434e+04
Hyundai          2.459704e+04
Infiniti         4.239421e+04
Kia              2.531017e+04
Lamborghini      3.315673e+05
Land Rover       6.782322e+04
Lexus            4.754907e+04
Lincoln          4.283983e+04
Lotus            6.918828e+04
Maserati         1.142077e+05
Maybach          5.462219e+05
Mazda            2.003938e+04
McLaren          2.398050e+05
Mercedes-Benz    7.147623e+04
Mitsubishi       2.124054e+04
Nissa

<h3><b>Question 4</b></h3>

Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?

In [22]:
q4Df = df[df['Year'] >= 2015]

In [23]:
q4Df['Engine HP'].isnull().sum()

51

<h3><b>Question 5</b></h3>

Calculate the average "Engine HP" in the dataset.

In [26]:
mean_hp_before = df['Engine HP'].mean()
mean_hp_before

249.38607007176023

Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.

In [27]:
df_tmp = df['Engine HP'].fillna('Engine HP', inplace=True)

Now, calcualte the average of "Engine HP" again.

In [30]:
df['Engine HP'].isnull().sum()

0

In [38]:
df = pn.read_csv(fname)

In [39]:
df['Engine HP'].isnull().sum()

69

In [40]:
df['Engine HP'].fillna(249.38, inplace=True)

In [41]:
mean_hp_after = df['Engine HP'].mean()
mean_hp_after

249.38603491690392

Round both means before answering this questions

In [42]:
print(round(mean_hp_before))
print(round(mean_hp_after))

249
249


<h3><b>Question 6</b></h3>

Select all the "Rolls-Royce" cars from the dataset.

In [43]:
df = pn.read_csv(fname)

In [46]:
RR_tmp = df[df['Make'] == 'Rolls-Royce']

Select only columns "Engine HP", "Engine Cylinders", "highway MPG".

In [48]:
RR = RR_tmp[['Engine HP','Engine Cylinders','highway MPG']]
RR

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5276       563.0              12.0           21
5277       563.0              12.0           21
5278       563.0              12.0           21
5279       563.0              12.0           20
5280       563.0              12.0           20
5281       563.0              12.0           21
5282       563.0              12.0           21
5283       563.0              12.0           21
5284       563.0              12.0           21
7443       322.0              12.0           15
7444       322.0              12.0           15
7553       453.0              12.0           19
7554       453.0              12.0           19
7555       453.0              12.0           19
7556       453.0              12.0           19
7557       453.0              12.0           19
7558       453.0              12.0           19
7559       453.0              12.0           19
7560       453.0              12.0           19
7561       453.0              12.0           19
7562       453.0              12.0           19
7563       453.0              12.0           19
7564       453.0              12.0           19
9431       322.0              12.0           15
9432       322.0              12.0           15
11448      624.0              12.0           21
11449      624.0              12.0           21
11450      624.0              12.0           21

Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).

In [49]:
RR = RR.drop_duplicates()

In [50]:
RR

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

Get the underlying NumPy array. Let's call it X

In [55]:
X = np.array(RR)

In [56]:
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX

In [57]:
XTX = X.T.dot(X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

Invert XTX

In [64]:
IXTX = np.linalg.inv(XTX)
IXTX

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

What's the sum of all the elements of the result?

In [65]:
IXTX.sum()

0.03221232067748617

<h3><b>Question 7</b></h3>

Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300]

In [66]:
y = np.array([[1000, 1100, 900, 1200, 1000, 850, 1300]])
y

array([[1000, 1100,  900, 1200, 1000,  850, 1300]])

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w

In [77]:
tmp = np.array(IXTX.dot(X.T))
tmp

array([[-0.00486592,  0.00336507, -0.00049461,  0.00143523, -0.00139492,
        -0.0023309 ,  0.00266407],
       [-0.19020088,  0.09362543, -0.08379139,  0.00491702,  0.22997159,
        -0.00609915, -0.02848958],
       [ 0.25164625, -0.13888652,  0.0729151 , -0.03298571, -0.09739786,
         0.07339609, -0.04480526]])

In [80]:
w = tmp.dot(y.T)
w

array([[ 0.19989598],
       [31.02612262],
       [31.65378877]])